### ISSUE TITLE
Параметры магазина

### ISSUE THREAD

**Issue by repsac-by** [migomby/b2b-api-doc#1]
1. Где получать параметры магазина, такие как Курс и Базовая валюта?
2. Нужен аналог кнопки "Подтвердить актуальность цен".

**Comment by migomby** [comment]
@repsac-by Добавили аналог кнопки: https://github.com/migomby/b2b-api-doc/wiki/%D0%98%D0%BC%D0%BF%D0%BE%D1%80%D1%82#get-importactual
В ближайшее время появится информация о магазине

**Comment by migomby** [comment]
@repsac-by добавили возможность получать информацию о магазине
https://github.com/migomby/b2b-api-doc/wiki/%D0%9C%D0%B0%D0%B3%D0%B0%D0%B7%D0%B8%D0%BD

**Comment by repsac-by** [comment]
Спасибо
